InvalidFormatException: correct empty invalidString.
Test passes again. An empty invalidString will be
set (instead of null) and the detail message will
feature the empty string (instead of using the default
detail message).