CardFormatException: define helper method for constructor.
Factor out some logic that determines which exceptions
message format to use based on a given “invalidString”
argument value.

This has the benefit of removing some ugly code in
the constructor that had to use a ternary operation
due to Java’s “first line” requirement for constructor
chaining.